### ISSUE TITLE
Runs fine locally, no data in PCF

### ISSUE THREAD

**Issue by dmfrey** [ordina-jworks/microservices-dashboard#101]
I setup a Spring Boot application to start the dashboard. It works fine locally. However, when I start it up in PCF, the interface loads, but no data is ever shown. Inspecting the interface, the data seems to get a 200 back. Any advice on diagnosing this?

**Comment by TYsewyn** [comment]
Hi @dmfrey 
Thanks for trying out our dashboard!

You can always check the logs of the dashboard server.

Is the server pointing to the right registry server?
The dashboard server will almost always return a result to the dashboard.
However, if the server isn't able to collect data you'll end up with an empty json array, which in turn will result in an empty dashboard.

HTH.

**Comment by dmfrey** [comment]
Didn't catch these in the logs before, but every service registered in eureka is throwing one of these when it attempts to get the `health` endpoint

    2016-12-15T09:56:34.74-0500 [APP/0]      OUT 2016-12-15 14:56:34.730 ERROR 10 --- [o-eventloop-3-1] b.o.m.nodes.aggregators.ErrorHandler     : Error retrieving node(s) for url https://[REDACTED]/health with headers [Host=[REDACTED], User-Agent=RxNetty Client]: java.io.IOException: Connection closed by peer before sending a response.
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT java.io.IOException: Connection closed by peer before sending a response.
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.reactivex.netty.protocol.http.client.ClientRequestResponseConverter.<clinit>(ClientRequestResponseConverter.java:91)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.reactivex.netty.protocol.http.client.ClientRequiredConfigurator.configureNewPipeline(ClientRequiredConfigurator.java:42)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.reactivex.netty.pipeline.PipelineConfiguratorComposite.configureNewPipeline(PipelineConfiguratorComposite.java:55)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.reactivex.netty.pipeline.PipelineConfiguratorComposite.configureNewPipeline(PipelineConfiguratorComposite.java:55)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.reactivex.netty.client.RxClientImpl$2.initChannel(RxClientImpl.java:127)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelRegisteredNow(ChannelHandlerInvokerUtil.java:32)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRegistered(DefaultChannelHandlerInvoker.java:50)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:114)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:833)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:417)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:477)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    2016-12-15T09:56:34.74-0500 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745)
    2016-12-15T09:56:34.87-0500 [APP/0]      OUT 2016-12-15 14:56:34.877  INFO 10 --- [o-eventloop-3-1] b.o.m.n.a.h.HealthIndicatorsAggregator   : Completed emission of a health node observable from url: https://[REDACTED]/health

**Comment by TYsewyn** [comment]
I'm going to close this issue since we're working on a new version.
If you still have any questions, don't hesitate to reach out on [Gitter](https://gitter.im/ordina-jworks/microservices-dashboard) or open a new issue!
