### ISSUE TITLE
Unable to run the simple project

### ISSUE THREAD

**Issue by qizha** [ordina-jworks/microservices-dashboard#99]
Hi there,
Not sure whether this is a known issue, when I  perform ./mvnw spring-boot:run in microservices-dashboard-simple, it ends up with the following error:
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.5.RELEASE:run (default-cli) on project microservices-dashboard-simple: An exception occurred while running. null: InvocationTargetException: Failed to process import candidates for configuration class [be.ordina.simple.MicroservicesDashboardSimpleApplication]; nested exception is java.lang.IllegalStateException: Error processing condition on be.ordina.msdashboard.config.RedisConfiguration: Could not resolve placeholder 'DOCKER_IP' in string value "${DOCKER_IP}" -> [Help 1]

Is there anything wrong in the code or I missed anything? Thanks

**Comment by Turbots** [comment]
Hello @qizha 
I have tried the sample myself just now (on Mac) and everyone still seems to be running OK.

Are you working on Windows? I know the embedded Redis server can be quite unstable on Windows.. The DOCKER_IP placeholder isn't present in our code, so I'm not sure where it comes from

**Comment by marqsab** [comment]
Hello

Same Error for me here

"Caused by: java.lang.IllegalStateException: Error processing condition on be.ordina.msdashboard.config.RedisConfiguration
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64) ~[spring-boot-autoconfigure-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:202) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:532) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	... 15 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'DOCKER_IP' in string value "${DOCKER_IP}""

I'm on a mac.

I just make a starter with start.spring.io (web + actuator + eurekadiscovery) put dependencies and launch a gradle bootRun.

any idea?

I don't understand why there is a DOCKER_IP in my error msg.

regards,

**Comment by Turbots** [comment]
I just created a new Spring Boot project from scratch with Web + Actuator + Eureka and setup my dependencies like this:

````
dependencies {
	compile('org.springframework.boot:spring-boot-starter-actuator')
	compile('org.springframework.cloud:spring-cloud-starter-eureka')
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('be.ordina:microservices-dashboard-server:1.0.1')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
````

Everything works fine on my Mac.

Could you show me your Gradle build file?

**Comment by marqsab** [comment]
Hello

here is my gradle file

`buildscript {
	ext {
		springBootVersion = '1.4.3.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

jar {
	baseName = 'dashboard-ms'
	version = '0.0.1-SNAPSHOT'
}

sourceCompatibility = 1.8

repositories {
	mavenCentral()
}


dependencies {
	compile('org.springframework.boot:spring-boot-starter-actuator')
	compile('org.springframework.cloud:spring-cloud-starter-eureka')
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile('org.springframework.boot:spring-boot-starter-test')
    compile "be.ordina:microservices-dashboard-server:1.0.1"
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Camden.SR4"
	}
}
`

**Comment by TYsewyn** [comment]
I'm closing this issue due to inactivity.
If you still have any questions, don't hesitate to reach out on Gitter or reopen this issue.
